[IV-23-24] Objetivo 3
moshidev/MaquiTracker.jl pull request #37
Opened 2023-11-28 11:42 UTC by moshidev

* [ ] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ] ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [ ] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2023-12-07 13:00 UTC, moshidev commented
En #27 está qué herramienta elegimos, por qué, y los pasos principales que hemos dado para que el repositorio acabe en el estado en el que está ahora mismo.

2023-12-11 07:18 UTC, JJ requested changes
Aparte de lo comentado, tendrías que dedicar un apartado separado a la gestión de dependencias. Una vez más, aunque sea la forma única de hacerlo, conviene que lo comentes explícitamente.

2023-12-11 07:18 UTC, JJ commented on docs/task_runner.md
> +Dadas las necesidades del proyecto actuales y potencialmente futuras dado el
No se trata de que enuncies "el mejor". Se trata de que presentes las diferentes opciones (siempre vas a tener task runners genéricos como `make`) y los criterios de elección y escojas uno de ellos de acuerdo con los criterios.

2023-12-11 07:18 UTC, JJ commented on docs/task_runner.md
> +A lo mejor no estoy entendiendo bien, o no estoy sabiendo buscar correctamente, pero entiendo que
En este objetivo se trata de que genéricamente sepáis buscar y justificar la elección de una herramienta, y *siempre* hay diferentes opciones (salvo casos muy concretos). Por eso debéis exponer *siempre* las opciones que hay, que siempre las va a haber.

2023-12-11 07:18 UTC, JJ commented on docs/task_runner.md
> +equivalentes. Podríamos proponer herramientas como `make`, `rake`, `maven`, pero en última instancia
`make` puede gestionar dependencias entre objetivos, o crear reglas automáticas para obtener código compilado a partir de fuente. Dudo mucho que Julia lo tenga.

2023-12-11 18:43 UTC, moshidev commented on docs/task_runner.md
> +Dadas las necesidades del proyecto actuales y potencialmente futuras dado el
#38

2023-12-11 18:43 UTC, moshidev commented on docs/task_runner.md
> +A lo mejor no estoy entendiendo bien, o no estoy sabiendo buscar correctamente, pero entiendo que
#38

2023-12-11 18:43 UTC, moshidev commented on docs/task_runner.md
> +equivalentes. Podríamos proponer herramientas como `make`, `rake`, `maven`, pero en última instancia
#38

2023-12-11 18:55 UTC, moshidev commented
Muchas gracias por haberlo revisado tan rápido, @JJ. ¿Cómo lo ves ahora?

2023-12-12 06:23 UTC, JJ approved these changes
:+1: 
No necesito decirte que vayas inmediatamente a por el objetivo siguiente, ¿no?

2023-12-12 08:53 UTC, merged